name: testData sfdx plugin testcases

on: [push]

jobs:
  build:
    name: testData sfdx plugin testcases
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    # prepare node environment and install dependencies
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    # build project
    - name: Build project
      run: yarn prepack
    # run tests
    - name : Run tests
      run: yarn test