name: testData sfdx plugin testcases

on: [push]

jobs:
  build:
    name: testData sfdx plugin testcases
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    # prepare node environment and install dependencies
    - name: Install Dependencies
    - uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: yarn install
    # build project
    - name: Build project
      run: yarn prepack
    # run tests
    - name : Run tests
      run: yarn test
    # submit to codecov cloud for coverage report
    - name: Submitting code coverage to codecov
      run: 
      command: |
            ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash